import { NextResponse } from "next/server";
import { requireRole } from "@/shared/server/api-helpers";
import { getPool } from "@/shared/server/db";
import { setMeta } from "@/shared/server/meta";
import { addAuditLog } from "@/features/audit-log/server/service";
import { roleLabel, nowStamp } from "@/shared/lib/roles";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function escapeIdentifier(identifier: string): string {
  return `\`${identifier.replace(/`/g, "``")}\``;
}

/**
 * Converts a MySQL value into a safe SQL literal.
 */
function escapeValue(value: unknown): string {
  if (value === null || value === undefined) {
    return "NULL";
  }

  if (Buffer.isBuffer(value)) {
    return `X'${value.toString("hex")}'`;
  }

  if (typeof value === "number") {
    if (!Number.isFinite(value)) return "NULL";
    return String(value);
  }

  if (typeof value === "bigint") {
    return value.toString();
  }

  if (typeof value === "boolean") {
    return value ? "1" : "0";
  }

  if (typeof value === "object") {
    if (value instanceof Date) {
      return `'${formatDate(value)}'`;
    }

    return escapeString(JSON.stringify(value));
  }

  return escapeString(String(value));
}

function escapeString(value: string): string {
  return `'${value
    .replace(/\\/g, "\\\\")
    .replace(/\0/g, "\\0")
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\x1a/g, "\\Z")
    .replace(/'/g, "\\'")}'`;
}

function formatDate(value: Date): string {
  const pad = (n: number) => String(n).padStart(2, "0");

  return (
    `${value.getFullYear()}-${pad(value.getMonth() + 1)}-${pad(value.getDate())} ` +
    `${pad(value.getHours())}:${pad(value.getMinutes())}:${pad(value.getSeconds())}`
  );
}

/**
 * Creates a complete SQL dump from the Railway MySQL database.
 *
 * This does not require mysqldump to be installed.
 */
async function createSqlBackup(): Promise<string> {
  const pool = getPool();

  const [databaseRows] = await pool.query<any[]>("SELECT DATABASE() AS database_name");

  const databaseName = databaseRows[0]?.database_name;

  if (!databaseName) {
    throw new Error("Unable to determine the connected database.");
  }

  const [tableRows] = await pool.query<any[]>(
    `
      SELECT TABLE_NAME
      FROM information_schema.TABLES
      WHERE TABLE_SCHEMA = ?
        AND TABLE_TYPE = 'BASE TABLE'
      ORDER BY TABLE_NAME
    `,
    [databaseName],
  );

  const tables = tableRows.map((row) => String(row.TABLE_NAME));

  if (tables.length === 0) {
    throw new Error("No database tables were found.");
  }

  const lines: string[] = [];

  lines.push("-- Employee 201 File Management System Database Backup");
  lines.push(`-- Database: ${databaseName}`);
  lines.push(`-- Created: ${new Date().toISOString()}`);
  lines.push("-- Generated by the Employee 201 FMS application");
  lines.push("");
  lines.push('SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";');
  lines.push("SET FOREIGN_KEY_CHECKS = 0;");
  lines.push("SET UNIQUE_CHECKS = 0;");
  lines.push("SET AUTOCOMMIT = 0;");
  lines.push("");

  for (const tableName of tables) {
    const table = escapeIdentifier(tableName);

    lines.push(`-- --------------------------------------------------------`);
    lines.push(`-- Table: ${tableName}`);
    lines.push(`-- --------------------------------------------------------`);
    lines.push("");

    const [createRows] = await pool.query<any[]>(`SHOW CREATE TABLE ${table}`);

    const createStatement = createRows[0]?.["Create Table"] ?? createRows[0]?.["Create View"];

    if (!createStatement) {
      throw new Error(`Could not read table definition for ${tableName}.`);
    }

    lines.push(`DROP TABLE IF EXISTS ${table};`);
    lines.push(`${createStatement};`);
    lines.push("");

    const [columnRows] = await pool.query<any[]>(`SHOW COLUMNS FROM ${table}`);

    // Exclude generated columns because MySQL calculates them automatically.
    const columns = columnRows
      .filter((column) => !String(column.Extra || "").includes("GENERATED"))
      .map((column) => String(column.Field));

    if (columns.length === 0) {
      continue;
    }

    const [dataRows] = await pool.query<any[]>(`SELECT * FROM ${table}`);

    if (dataRows.length === 0) {
      lines.push(`-- No rows in ${tableName}.`);
      lines.push("");
      continue;
    }

    const columnList = columns.map(escapeIdentifier).join(", ");

    // Insert in batches so very large tables don't create one enormous INSERT.
    const BATCH_SIZE = 500;

    for (let start = 0; start < dataRows.length; start += BATCH_SIZE) {
      const batch = dataRows.slice(start, start + BATCH_SIZE);

      const values = batch.map((row) => {
        const rowValues = columns.map((column) => escapeValue(row[column]));

        return `(${rowValues.join(", ")})`;
      });

      lines.push(`INSERT INTO ${table} (${columnList}) VALUES`);

      lines.push(`${values.join(",\n")};`);
      lines.push("");
    }
  }

  lines.push("COMMIT;");
  lines.push("SET UNIQUE_CHECKS = 1;");
  lines.push("SET FOREIGN_KEY_CHECKS = 1;");
  lines.push("");

  return lines.join("\n");
}

export async function POST() {
  const user = await requireRole("admin");

  if (user instanceof NextResponse) {
    return user;
  }

  try {
    const sql = await createSqlBackup();

    const stamp = nowStamp();

    await setMeta("lastBackup", stamp);

    await addAuditLog(user.name, roleLabel(user.role), "Completed a full database backup");

    const filename = `e201_fms_backup_${new Date().toISOString().replace(/[:.]/g, "-")}.sql`;

    return new Response(sql, {
      status: 200,
      headers: {
        "Content-Type": "application/sql; charset=utf-8",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Cache-Control": "no-store",
        // Matches what AppContext.tsx's backupNow() reads via
        // res.headers.get('X-Backup-Stamp') — must stay in sync with that file.
        "X-Backup-Stamp": stamp,
      },
    });
  } catch (error) {
    console.error("Database backup failed:", error);

    return NextResponse.json(
      {
        error: error instanceof Error ? error.message : "Database backup failed.",
      },
      { status: 500 },
    );
  }
}
